title: IGS Research
email: andysong1616@gmail.com
baseurl: "/igs-research"
url: "https://ingyu-song.github.io"
permalink: /:categories/:title/

markdown: kramdown
theme: null

plugins:
  - jekyll-feed

collections:
  sector:
    output: true
  memo:
    output: true
