title: IGS Research
email: andysong1616@gmail.com
baseurl: "/igs-research"
url: "https://ingyu-song.github.io"
markdown: kramdown
theme: null
plugins:
  - jekyll-feed
future: true
collections:
  sector:
    output: true
    permalink: /sector/:name/
  memo:
    output: true
    permalink: /memo/:name/
defaults:
  - scope:
      path: ""
      type: "memo"
    values:
      layout: "memo"
